keycloak:
  image: quay.io/keycloak/keycloak:11.0.2
  ports:
  - "8080:8080"
  volumes:
  - ./themes/ilhasoft/:/opt/jboss/keycloak/themes/ilhasoft/
  environment:
    KEYCLOAK_USER: "admin"
    KEYCLOAK_PASSWORD: "admin"
